/* Generated By:JJTree&JavaCC: Do not edit this line. ELParserConstants.java */
package org.apache.el.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ELParserConstants {

  /** End of File. */
  public int EOF = 0;
  /** RegularExpression Id. */
  public int LITERAL_EXPRESSION = 1;
  /** RegularExpression Id. */
  public int START_DYNAMIC_EXPRESSION = 2;
  /** RegularExpression Id. */
  public int START_DEFERRED_EXPRESSION = 3;
  /** RegularExpression Id. */
  public int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  public int FLOATING_POINT_LITERAL = 9;
  /** RegularExpression Id. */
  public int EXPONENT = 10;
  /** RegularExpression Id. */
  public int STRING_LITERAL = 11;
  /** RegularExpression Id. */
  public int TRUE = 12;
  /** RegularExpression Id. */
  public int FALSE = 13;
  /** RegularExpression Id. */
  public int NULL = 14;
  /** RegularExpression Id. */
  public int END_EXPRESSION = 15;
  /** RegularExpression Id. */
  public int DOT = 16;
  /** RegularExpression Id. */
  public int LPAREN = 17;
  /** RegularExpression Id. */
  public int RPAREN = 18;
  /** RegularExpression Id. */
  public int LBRACK = 19;
  /** RegularExpression Id. */
  public int RBRACK = 20;
  /** RegularExpression Id. */
  public int COLON = 21;
  /** RegularExpression Id. */
  public int COMMA = 22;
  /** RegularExpression Id. */
  public int GT0 = 23;
  /** RegularExpression Id. */
  public int GT1 = 24;
  /** RegularExpression Id. */
  public int LT0 = 25;
  /** RegularExpression Id. */
  public int LT1 = 26;
  /** RegularExpression Id. */
  public int GE0 = 27;
  /** RegularExpression Id. */
  public int GE1 = 28;
  /** RegularExpression Id. */
  public int LE0 = 29;
  /** RegularExpression Id. */
  public int LE1 = 30;
  /** RegularExpression Id. */
  public int EQ0 = 31;
  /** RegularExpression Id. */
  public int EQ1 = 32;
  /** RegularExpression Id. */
  public int NE0 = 33;
  /** RegularExpression Id. */
  public int NE1 = 34;
  /** RegularExpression Id. */
  public int NOT0 = 35;
  /** RegularExpression Id. */
  public int NOT1 = 36;
  /** RegularExpression Id. */
  public int AND0 = 37;
  /** RegularExpression Id. */
  public int AND1 = 38;
  /** RegularExpression Id. */
  public int OR0 = 39;
  /** RegularExpression Id. */
  public int OR1 = 40;
  /** RegularExpression Id. */
  public int EMPTY = 41;
  /** RegularExpression Id. */
  public int INSTANCEOF = 42;
  /** RegularExpression Id. */
  public int MULT = 43;
  /** RegularExpression Id. */
  public int PLUS = 44;
  /** RegularExpression Id. */
  public int MINUS = 45;
  /** RegularExpression Id. */
  public int QUESTIONMARK = 46;
  /** RegularExpression Id. */
  public int DIV0 = 47;
  /** RegularExpression Id. */
  public int DIV1 = 48;
  /** RegularExpression Id. */
  public int MOD0 = 49;
  /** RegularExpression Id. */
  public int MOD1 = 50;
  /** RegularExpression Id. */
  public int IDENTIFIER = 51;
  /** RegularExpression Id. */
  public int FUNCTIONSUFFIX = 52;
  /** RegularExpression Id. */
  public int IMPL_OBJ_START = 53;
  /** RegularExpression Id. */
  public int LETTER = 54;
  /** RegularExpression Id. */
  public int DIGIT = 55;
  /** RegularExpression Id. */
  public int ILLEGAL_CHARACTER = 56;

  /** Lexical state. */
  public int DEFAULT = 0;
  /** Lexical state. */
  public int IN_EXPRESSION = 1;

  /** Literal token values. */
  public String[] tokenImage = {
    "<EOF>",
    "<LITERAL_EXPRESSION>",
    "\"${\"",
    "\"#{\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"}\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\">\"",
    "\"gt\"",
    "\"<\"",
    "\"lt\"",
    "\">=\"",
    "\"ge\"",
    "\"<=\"",
    "\"le\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\"!\"",
    "\"not\"",
    "\"&&\"",
    "\"and\"",
    "\"||\"",
    "\"or\"",
    "\"empty\"",
    "\"instanceof\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"/\"",
    "\"div\"",
    "\"%\"",
    "\"mod\"",
    "<IDENTIFIER>",
    "<FUNCTIONSUFFIX>",
    "\"#\"",
    "<LETTER>",
    "<DIGIT>",
    "<ILLEGAL_CHARACTER>",
  };
}
